title: athulinks
author: Athul Sudheesh
description: > # this means to ignore newlines until "baseurl:"
  Blog of Athul Sudheesh
  Athul Sudheesh is a Cognitive Neuroscienitst, specialized in Computational Modelling,
   interested in Brain Computer Interfaces and the philosophy of the mind.
social_sites:
  twitter: AthulSudheesh
  github:  athulsudheesh
  #dribbble: jekyll
  #facebook:
  #flickr: jekyll
  #instagram: jekyll
  #linkedin: jekyll
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll
rss: rss
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: athulinks
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
  #date_format: "%b %-d, %Y"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tagging
  - jekyll-archives
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

markdown: kramdown
google_analytics: UA-112766072-1
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
