title: athulinks
author: Athul Sudheesh
description: > # this means to ignore newlines until "baseurl:"
  Blog of Athul Sudheesh
social_sites:
  twitter: AthulSudheesh
  github:  athulsudheesh
  #dribbble: jekyll
  facebook: AthulSudheesh01
  #flickr: jekyll
  linkedin: athulsudheesh
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll

rss: rss

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: athulinks

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
